name: AITemplate_ci

on:
  push:
    branches:
      - ci-setup
  pull_request:
    branches:
      - ci-setup

jobs:
  build:
    runs-on: rocm

    steps:
    - uses: actions/checkout@v2
    - name: Get CPU info on Ubuntu
      if: contains(runner.os, 'linux')
      run: |
        cat /proc/cpuinfo
    - name: Get env vars
      run: |
        echo GITHUB_WORKFLOW   = $GITHUB_WORKFLOW
        echo HOME              = $HOME
        echo GITHUB_ACTION     = $GITHUB_ACTION
        echo GITHUB_ACTIONS    = $GITHUB_ACTIONS
        echo GITHUB_REPOSITORY = $GITHUB_REPOSITORY
        echo GITHUB_EVENT_NAME = $GITHUB_EVENT_NAME
        echo GITHUB_EVENT_PATH = $GITHUB_EVENT_PATH
        echo GITHUB_WORKSPACE  = $GITHUB_WORKSPACE
        echo GITHUB_SHA        = $GITHUB_SHA
        echo GITHUB_REF        = $GITHUB_REF
        c++ --verbose
    - name: Build and Test AITemplate
      run: |
        rocm-smi
        rocminfo | grep "gfx"
        git clone --recursive -b ci-setup https://github.com/ROCmSoftwarePlatform/AITemplate.git
        cd AITemplate
        DOCKER_BUILDKIT=1 ./docker/build.sh rocm
        docker run --network=host --device=/dev/kfd --device=/dev/dri --ipc=host --group-add video --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v $HOME:/dockerx/ ait:latest
        export ROCM_PATH=/opt/rocm
        export ROC_USE_FGS_KERNARG=0
        # clean up and reinstall ait
        pip3 uninstall -y aitemplate
        cd python
        rm -rf dist build
        python3 setup.py bdist_wheel
        pip3 install dist/*.whl
        #install necessary python modules
        pip3 install timm
        pip3 uninstall -y torch 
        pip3 install torch --extra-index-url https://download.pytorch.org/whl/rocm5.1.1
        python3 -m pip install transformers click
        python3 -c "import torch; print(torch.__version__)"
        #run examples
        cd ../examples/01_resnet-50/
        echo "Running RESNET50 tests"
        HIP_VISIBLE_DEVICES=0,1 python3 benchmark_ait.py 2>&1 | tee resnet50.log
        # test 2 gcd
        for BATCH_SIZE in 1 2 4 8 16 32 64 128 256
        do
          HIP_VISIBLE_DEVICES=0 python3 benchmark_ait.py --batch-size $BATCH_SIZE 2>&1 | tee -a resnet50.log &
          HIP_VISIBLE_DEVICES=1 python3 benchmark_ait.py --batch-size $BATCH_SIZE 2>&1 | tee -a resnet50.log
        done
        ## BERT
        #cd ../03_bert/
        echo "BERT tests are temporarily disabled"
        # profiling
        #HIP_VISIBLE_DEVICES=0,1 python3 benchmark_ait.py
        # # test 2 gcd
        #for SEQ_LENGTH in 64 128 384 1024 4096
        #do
        #for BATCH_SIZE in 1 2 4 8 16 32 64 128 256
        #do
        #    HIP_VISIBLE_DEVICES=0 python3 benchmark_ait.py --batch-size $BATCH_SIZE --seq-length $SEQ_LENGTH &
        #    HIP_VISIBLE_DEVICES=1 python3 benchmark_ait.py --batch-size $BATCH_SIZE --seq-length $SEQ_LENGTH
        #done
        #done
        # VIT
        cd ../04_vit
        echo "Running VIT tests"
        # profiling
        HIP_VISIBLE_DEVICES=0,1 python3 benchmark_ait.py 2>&1 | tee vit.log
        # test 2 gcd
        for BATCH_SIZE in 1 2 4 8 16 32 64 128 256
        do
           HIP_VISIBLE_DEVICES=0 python3 benchmark_ait.py --batch-size $BATCH_SIZE 2>&1 | tee -a vit.log &
           HIP_VISIBLE_DEVICES=1 python3 benchmark_ait.py --batch-size $BATCH_SIZE 2>&1 | tee -a vit.log
        done
        echo "Process the test results"

